name: Git Tag
description: A Buildkite plugin to tag the current git repository with a specific value
author: https://github.com/nicwise
requirements: [git]
configuration:
  required: 
    - version
  properties:
    version:
      type: string
    message:
      type: string
    githubtoken:
      type: string
    reponame:
      type: string
    prerelease:
      type: boolean
    draft:
      type: boolean
    user:
      properties:
        email:
          type: string
        name:
          type: string
