steps:
  - label: ":hammer: Test"
    plugins:
      docker-compose#v1.3.1:
        run: tests
  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: tendnz/git-tag
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**
