#!/usr/bin/env bash

set -euo pipefail

if [[ ${BUILDKITE_COMMAND_EXIT_STATUS:-0} != "0" ]]
then
  echo "--- Skipping git-tag because the command failed"
  exit 0
fi

branch=${BUILDKITE_PLUGIN_GIT_TAG_BRANCH:-${BUILDKITE_BRANCH}}
message=${BUILDKITE_PLUGIN_GIT_TAG_MESSAGE:-"Build #${BUILDKITE_BUILD_NUMBER}"}
username=${BUILDKITE_PLUGIN_GIT_TAG_USER_0_NAME:-${BUILDKITE_BUILD_AUTHOR}}
email=${BUILDKITE_PLUGIN_GIT_TAG_USER_0_EMAIL:-${BUILDKITE_BUILD_AUTHOR_EMAIL}}

echo "--- Setting username - ${username}"
git config user.name "$username"
echo "--- Setting email - ${email}"
git config user.email "$email"

echo "--- Tagging with ${BUILDKITE_PLUGIN_GIT_TAG_VERSION}"
git tag "${BUILDKITE_PLUGIN_GIT_TAG_VERSION}" -m "${message}"
git push --tags
echo "--- Tags pushed"

if [[ -n $BUILDKITE_PLUGIN_GIT_TAG_GITHUBTOKEN ]]; then
  echo "--- Making a release"


  generate_post_data()
  {
    cat <<EOF
{
  "tag_name": "$BUILDKITE_PLUGIN_GIT_TAG_VERSION",
  "name": "$BUILDKITE_PLUGIN_GIT_TAG_VERSION",
  "body": "$BUILDKITE_PLUGIN_GIT_TAG_MESSAGE"
}
EOF
  }

  echo "Create release $BUILDKITE_PLUGIN_GIT_TAG_VERSION for repo: $BUILDKITE_PLUGIN_GIT_TAG_REPONAME"
  echo "$(generate_post_data)"
  echo "https://api.github.com/repos/$BUILDKITE_PLUGIN_GIT_TAG_REPONAME/releases"
  env
  curl --data "$(generate_post_data)" "https://api.github.com/repos/$BUILDKITE_PLUGIN_GIT_TAG_REPONAME/releases?access_token=$BUILDKITE_PLUGIN_GIT_TAG_GITHUBTOKEN"

fi
